services:
  frontend:
    build:
      context: .
      dockerfile: apps/web/Dockerfile
    ports:
      - "8888:8888"
    depends_on:
      - backend
    environment:
      - VITE_BASE_PATH=http://localhost
      - VITE_SERVER_PORT=8080

  backend:
    build:
      context: .
      dockerfile: apps/api/Dockerfile
    ports:
      - "8080:8080"
